#ifndef RESPONSES_CONSTANTS_H
#define RESPONSES_CONSTANTS_H

#define CONNACK_CONNECTION_ACCEPTED 0x00
#define CONNACK_REFUSED_NOT_AUTHORIZED 0x05
#define CONNACK_REFUSED_IDENTIFIER_REJECTED 0x02

#endif